### ISSUE TITLE
Issue with "sudo -H pip3 install -U py3coap"

### ISSUE THREAD

**Issue by SANCLA** [moroen/IKEA-Tradfri-plugin#104]
Raspberry Pi 4 (2GB model with 16GB sd-card) 
Raspberry Pi OS Lite 4.19 (release date 2020-05-27)
Domoticz Stable 2020.2 (compile date Apr 27 2020)

Clean install with only the latest Raspberry Pi OS, followed by this installation:

SSH Dump:
```
pi@raspberrypi:~ $ sudo systemctl stop domoticz.service
pi@raspberrypi:~ $ sudo apt update -y && sudo apt upgrade -y
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  rpi-eeprom-images
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $ sudo apt install golang python3 python3-dev python3-pip -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3 is already the newest version (3.7.3-1).
python3 set to manually installed.
The following package was automatically installed and is no longer required:
  rpi-eeprom-images
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  dh-python gir1.2-glib-2.0 golang-1.11 golang-1.11-doc golang-1.11-go golang-1.11-src golang-doc golang-go golang-src libexpat1-dev
  libgirepository-1.0-1 libpython3-dev libpython3.7-dev python-pip-whl python3-asn1crypto python3-cffi-backend python3-crypto python3-cryptography
  python3-dbus python3-distutils python3-entrypoints python3-gi python3-keyring python3-keyrings.alt python3-lib2to3 python3-secretstorage
  python3-setuptools python3-wheel python3-xdg python3.7-dev
Suggested packages:
  bzr | brz mercurial subversion python-crypto-doc python-cryptography-doc python3-cryptography-vectors python-dbus-doc python3-dbus-dbg
  gnome-keyring libkf5wallet-bin gir1.2-gnomekeyring-1.0 python-secretstorage-doc python-setuptools-doc
The following NEW packages will be installed:
  dh-python gir1.2-glib-2.0 golang golang-1.11 golang-1.11-doc golang-1.11-go golang-1.11-src golang-doc golang-go golang-src libexpat1-dev
  libgirepository-1.0-1 libpython3-dev libpython3.7-dev python-pip-whl python3-asn1crypto python3-cffi-backend python3-crypto python3-cryptography
  python3-dbus python3-dev python3-distutils python3-entrypoints python3-gi python3-keyring python3-keyrings.alt python3-lib2to3 python3-pip
  python3-secretstorage python3-setuptools python3-wheel python3-xdg python3.7-dev
0 upgraded, 33 newly installed, 0 to remove and 0 not upgraded.
Need to get 103 MB of archives.
After this operation, 342 MB of additional disk space will be used.
Get:1 http://archive.raspberrypi.org/debian buster/main armhf python-pip-whl all 18.1-5+rpt1 [1,591 kB]
Get:3 http://archive.raspberrypi.org/debian buster/main armhf python3-pip all 18.1-5+rpt1 [171 kB]
Get:2 http://mirror.serverius.net/raspbian/raspbian buster/main armhf python3-lib2to3 all 3.7.3-1 [76.7 kB]
Get:4 http://mirror.serverius.net/raspbian/raspbian buster/main armhf python3-distutils all 3.7.3-1 [142 kB]
Get:5 http://mirror.serverius.net/raspbian/raspbian buster/main armhf dh-python all 3.20190308 [99.3 kB]
Get:6 http://mirror.serverius.net/raspbian/raspbian buster/main armhf libgirepository-1.0-1 armhf 1.58.3-2 [78.8 kB]
Get:7 http://mirror.serverius.net/raspbian/raspbian buster/main armhf gir1.2-glib-2.0 armhf 1.58.3-2 [143 kB]
Get:8 http://mirror.serverius.net/raspbian/raspbian buster/main armhf golang-1.11-src armhf 1.11.6-1+rpi1+deb10u2 [13.0 MB]
Get:9 http://mirror.serverius.net/raspbian/raspbian buster/main armhf golang-1.11-go armhf 1.11.6-1+rpi1+deb10u2 [36.3 MB]
Get:25 http://raspbian.raspberrypi.org/raspbian buster/main armhf python3-dev armhf 3.7.3-1 [1,264 B]
Get:10 http://mirror.serverius.net/raspbian/raspbian buster/main armhf golang-1.11-doc all 1.11.6-1+rpi1+deb10u2 [2,517 kB]
Get:11 http://mirror.serverius.net/raspbian/raspbian buster/main armhf golang-1.11 all 1.11.6-1+rpi1+deb10u2 [24.1 kB]
Get:12 http://mirror.serverius.net/raspbian/raspbian buster/main armhf golang-src armhf 2:1.11~1+b6 [4,660 B]
Get:13 http://mirror.serverius.net/raspbian/raspbian buster/main armhf golang-go armhf 2:1.11~1+b6 [23.7 kB]
Get:14 http://mirror.serverius.net/raspbian/raspbian buster/main armhf golang-doc all 2:1.11~1 [4,392 B]
Get:15 http://mirror.serverius.net/raspbian/raspbian buster/main armhf golang armhf 2:1.11~1+b6 [4,612 B]
Get:16 http://mirror.serverius.net/raspbian/raspbian buster/main armhf libexpat1-dev armhf 2.2.6-2+deb10u1 [127 kB]
Get:17 http://mirror.serverius.net/raspbian/raspbian buster/main armhf libpython3.7-dev armhf 3.7.3-2+deb10u1 [47.2 MB]
Get:18 http://mirror.serverius.net/raspbian/raspbian buster/main armhf libpython3-dev armhf 3.7.3-1 [20.1 kB]
Get:19 http://mirror.serverius.net/raspbian/raspbian buster/main armhf python3-asn1crypto all 0.24.0-1 [78.2 kB]
Get:20 http://mirror.serverius.net/raspbian/raspbian buster/main armhf python3-cffi-backend armhf 1.12.2-1 [70.1 kB]
Get:21 http://mirror.serverius.net/raspbian/raspbian buster/main armhf python3-crypto armhf 2.6.1-9+b1 [251 kB]
Get:22 http://mirror.serverius.net/raspbian/raspbian buster/main armhf python3-cryptography armhf 2.6.1-3+deb10u2 [184 kB]
Get:23 http://mirror.serverius.net/raspbian/raspbian buster/main armhf python3-dbus armhf 1.2.8-3 [95.9 kB]
Get:24 http://mirror.serverius.net/raspbian/raspbian buster/main armhf python3.7-dev armhf 3.7.3-2+deb10u1 [522 kB]
Get:26 http://mirror.serverius.net/raspbian/raspbian buster/main armhf python3-entrypoints all 0.3-1 [5,508 B]
Get:27 http://mirror.serverius.net/raspbian/raspbian buster/main armhf python3-gi armhf 3.30.4-1 [161 kB]
Get:28 http://mirror.serverius.net/raspbian/raspbian buster/main armhf python3-secretstorage all 2.3.1-2 [14.2 kB]
Get:29 http://mirror.serverius.net/raspbian/raspbian buster/main armhf python3-keyring all 17.1.1-1 [43.1 kB]
Get:30 http://mirror.serverius.net/raspbian/raspbian buster/main armhf python3-keyrings.alt all 3.1.1-1 [18.2 kB]
Get:31 http://mirror.serverius.net/raspbian/raspbian buster/main armhf python3-setuptools all 40.8.0-1 [306 kB]
Get:32 http://mirror.serverius.net/raspbian/raspbian buster/main armhf python3-wheel all 0.32.3-2 [19.4 kB]
Get:33 http://mirror.serverius.net/raspbian/raspbian buster/main armhf python3-xdg all 0.25-5 [35.9 kB]
Fetched 103 MB in 10s (10.7 MB/s)
Extracting templates from packages: 100%
Selecting previously unselected package python3-lib2to3.
(Reading database ... 40863 files and directories currently installed.)
Preparing to unpack .../00-python3-lib2to3_3.7.3-1_all.deb ...
Unpacking python3-lib2to3 (3.7.3-1) ...
Selecting previously unselected package python3-distutils.
Preparing to unpack .../01-python3-distutils_3.7.3-1_all.deb ...
Unpacking python3-distutils (3.7.3-1) ...
Selecting previously unselected package dh-python.
Preparing to unpack .../02-dh-python_3.20190308_all.deb ...
Unpacking dh-python (3.20190308) ...
Selecting previously unselected package libgirepository-1.0-1:armhf.
Preparing to unpack .../03-libgirepository-1.0-1_1.58.3-2_armhf.deb ...
Unpacking libgirepository-1.0-1:armhf (1.58.3-2) ...
Selecting previously unselected package gir1.2-glib-2.0:armhf.
Preparing to unpack .../04-gir1.2-glib-2.0_1.58.3-2_armhf.deb ...
Unpacking gir1.2-glib-2.0:armhf (1.58.3-2) ...
Selecting previously unselected package golang-1.11-src.
Preparing to unpack .../05-golang-1.11-src_1.11.6-1+rpi1+deb10u2_armhf.deb ...
Unpacking golang-1.11-src (1.11.6-1+rpi1+deb10u2) ...
Selecting previously unselected package golang-1.11-go.
Preparing to unpack .../06-golang-1.11-go_1.11.6-1+rpi1+deb10u2_armhf.deb ...
Unpacking golang-1.11-go (1.11.6-1+rpi1+deb10u2) ...
Selecting previously unselected package golang-1.11-doc.
Preparing to unpack .../07-golang-1.11-doc_1.11.6-1+rpi1+deb10u2_all.deb ...
Unpacking golang-1.11-doc (1.11.6-1+rpi1+deb10u2) ...
Selecting previously unselected package golang-1.11.
Preparing to unpack .../08-golang-1.11_1.11.6-1+rpi1+deb10u2_all.deb ...
Unpacking golang-1.11 (1.11.6-1+rpi1+deb10u2) ...
Selecting previously unselected package golang-src.
Preparing to unpack .../09-golang-src_2%3a1.11~1+b6_armhf.deb ...
Unpacking golang-src (2:1.11~1+b6) ...
Selecting previously unselected package golang-go.
Preparing to unpack .../10-golang-go_2%3a1.11~1+b6_armhf.deb ...
Unpacking golang-go (2:1.11~1+b6) ...
Selecting previously unselected package golang-doc.
Preparing to unpack .../11-golang-doc_2%3a1.11~1_all.deb ...
Unpacking golang-doc (2:1.11~1) ...
Selecting previously unselected package golang.
Preparing to unpack .../12-golang_2%3a1.11~1+b6_armhf.deb ...
Unpacking golang (2:1.11~1+b6) ...
Selecting previously unselected package libexpat1-dev:armhf.
Preparing to unpack .../13-libexpat1-dev_2.2.6-2+deb10u1_armhf.deb ...
Unpacking libexpat1-dev:armhf (2.2.6-2+deb10u1) ...
Selecting previously unselected package libpython3.7-dev:armhf.
Preparing to unpack .../14-libpython3.7-dev_3.7.3-2+deb10u1_armhf.deb ...
Unpacking libpython3.7-dev:armhf (3.7.3-2+deb10u1) ...
Selecting previously unselected package libpython3-dev:armhf.
Preparing to unpack .../15-libpython3-dev_3.7.3-1_armhf.deb ...
Unpacking libpython3-dev:armhf (3.7.3-1) ...
Selecting previously unselected package python-pip-whl.
Preparing to unpack .../16-python-pip-whl_18.1-5+rpt1_all.deb ...
Unpacking python-pip-whl (18.1-5+rpt1) ...
Selecting previously unselected package python3-asn1crypto.
Preparing to unpack .../17-python3-asn1crypto_0.24.0-1_all.deb ...
Unpacking python3-asn1crypto (0.24.0-1) ...
Selecting previously unselected package python3-cffi-backend.
Preparing to unpack .../18-python3-cffi-backend_1.12.2-1_armhf.deb ...
Unpacking python3-cffi-backend (1.12.2-1) ...
Selecting previously unselected package python3-crypto.
Preparing to unpack .../19-python3-crypto_2.6.1-9+b1_armhf.deb ...
Unpacking python3-crypto (2.6.1-9+b1) ...
Selecting previously unselected package python3-cryptography.
Preparing to unpack .../20-python3-cryptography_2.6.1-3+deb10u2_armhf.deb ...
Unpacking python3-cryptography (2.6.1-3+deb10u2) ...
Selecting previously unselected package python3-dbus.
Preparing to unpack .../21-python3-dbus_1.2.8-3_armhf.deb ...
Unpacking python3-dbus (1.2.8-3) ...
Selecting previously unselected package python3.7-dev.
Preparing to unpack .../22-python3.7-dev_3.7.3-2+deb10u1_armhf.deb ...
Unpacking python3.7-dev (3.7.3-2+deb10u1) ...
Selecting previously unselected package python3-dev.
Preparing to unpack .../23-python3-dev_3.7.3-1_armhf.deb ...
Unpacking python3-dev (3.7.3-1) ...
Selecting previously unselected package python3-entrypoints.
Preparing to unpack .../24-python3-entrypoints_0.3-1_all.deb ...
Unpacking python3-entrypoints (0.3-1) ...
Selecting previously unselected package python3-gi.
Preparing to unpack .../25-python3-gi_3.30.4-1_armhf.deb ...
Unpacking python3-gi (3.30.4-1) ...
Selecting previously unselected package python3-secretstorage.
Preparing to unpack .../26-python3-secretstorage_2.3.1-2_all.deb ...
Unpacking python3-secretstorage (2.3.1-2) ...
Selecting previously unselected package python3-keyring.
Preparing to unpack .../27-python3-keyring_17.1.1-1_all.deb ...
Unpacking python3-keyring (17.1.1-1) ...
Selecting previously unselected package python3-keyrings.alt.
Preparing to unpack .../28-python3-keyrings.alt_3.1.1-1_all.deb ...
Unpacking python3-keyrings.alt (3.1.1-1) ...
Selecting previously unselected package python3-pip.
Preparing to unpack .../29-python3-pip_18.1-5+rpt1_all.deb ...
Unpacking python3-pip (18.1-5+rpt1) ...
Selecting previously unselected package python3-setuptools.
Preparing to unpack .../30-python3-setuptools_40.8.0-1_all.deb ...
Unpacking python3-setuptools (40.8.0-1) ...
Selecting previously unselected package python3-wheel.
Preparing to unpack .../31-python3-wheel_0.32.3-2_all.deb ...
Unpacking python3-wheel (0.32.3-2) ...
Selecting previously unselected package python3-xdg.
Preparing to unpack .../32-python3-xdg_0.25-5_all.deb ...
Unpacking python3-xdg (0.25-5) ...
Setting up python3-entrypoints (0.3-1) ...
Setting up python3-dbus (1.2.8-3) ...
Setting up golang-1.11-src (1.11.6-1+rpi1+deb10u2) ...
Setting up python3-xdg (0.25-5) ...
Setting up python3-wheel (0.32.3-2) ...
Setting up golang-1.11-go (1.11.6-1+rpi1+deb10u2) ...
Setting up libexpat1-dev:armhf (2.2.6-2+deb10u1) ...
Setting up python3-crypto (2.6.1-9+b1) ...
Setting up libgirepository-1.0-1:armhf (1.58.3-2) ...
Setting up python-pip-whl (18.1-5+rpt1) ...
Setting up golang-src (2:1.11~1+b6) ...
Setting up python3-lib2to3 (3.7.3-1) ...
Setting up python3-asn1crypto (0.24.0-1) ...
Setting up python3-cffi-backend (1.12.2-1) ...
Setting up python3-distutils (3.7.3-1) ...
Setting up dh-python (3.20190308) ...
Setting up python3-setuptools (40.8.0-1) ...
Setting up golang-1.11-doc (1.11.6-1+rpi1+deb10u2) ...
Setting up golang-go (2:1.11~1+b6) ...
Setting up libpython3.7-dev:armhf (3.7.3-2+deb10u1) ...
Setting up python3.7-dev (3.7.3-2+deb10u1) ...
Setting up python3-cryptography (2.6.1-3+deb10u2) ...
Setting up golang-1.11 (1.11.6-1+rpi1+deb10u2) ...
Setting up gir1.2-glib-2.0:armhf (1.58.3-2) ...
Setting up python3-pip (18.1-5+rpt1) ...
Setting up python3-keyrings.alt (3.1.1-1) ...
Setting up golang-doc (2:1.11~1) ...
Setting up golang (2:1.11~1+b6) ...
Setting up libpython3-dev:armhf (3.7.3-1) ...
Setting up python3-secretstorage (2.3.1-2) ...
Setting up python3-dev (3.7.3-1) ...
Setting up python3-gi (3.30.4-1) ...
Setting up python3-keyring (17.1.1-1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...
pi@raspberrypi:~ $ cd /home/pi/domoticz/plugins/
pi@raspberrypi:~/domoticz/plugins $ ls
AwoxSMP  examples
pi@raspberrypi:~/domoticz/plugins $ rm -rf IKEA-Tradfri/
pi@raspberrypi:~/domoticz/plugins $ ls
AwoxSMP  examples
pi@raspberrypi:~/domoticz/plugins $ git clone https://github.com/moroen/IKEA-Tradfri-plugin.git IKEA-Tradfri
Cloning into 'IKEA-Tradfri'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 1164 (delta 24), reused 30 (delta 14), pack-reused 1119
Receiving objects: 100% (1164/1164), 283.63 KiB | 1.07 MiB/s, done.
Resolving deltas: 100% (692/692), done.
pi@raspberrypi:~/domoticz/plugins $ cd IKEA-Tradfri
pi@raspberrypi:~/domoticz/plugins/IKEA-Tradfri $ sudo -H pip3 install --upgrade pip
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pip
  Downloading https://files.pythonhosted.org/packages/43/84/23ed6a1796480a6f1a2d38f2802901d078266bda38388954d01d3f2e821d/pip-20.1.1-py2.py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 293kB/s
Installing collected packages: pip
  Found existing installation: pip 18.1
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pip'. No files were found to uninstall.
Successfully installed pip-20.1.1
pi@raspberrypi:~/domoticz/plugins/IKEA-Tradfri $ sudo -H pip3 install --upgrade setuptools
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting setuptools
  Downloading setuptools-47.1.1-py3-none-any.whl (583 kB)
     |████████████████████████████████| 583 kB 5.7 MB/s
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 40.8.0
    Uninstalling setuptools-40.8.0:
      Successfully uninstalled setuptools-40.8.0
Successfully installed setuptools-47.1.1
pi@raspberrypi:~/domoticz/plugins/IKEA-Tradfri $ sudo -H pip3 install -U py3coap
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting py3coap
  Downloading py3coap-0.8.0.tar.gz (5.3 kB)
Building wheels for collected packages: py3coap
  Building wheel for py3coap (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c6o1hici/py3coap/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c6o1hici/py3coap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-963kvj6r
       cwd: /tmp/pip-install-c6o1hici/py3coap/
  Complete output (53 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-3.7
  creating build/lib.linux-armv7l-3.7/py3coap
  copying py3coap/errors.py -> build/lib.linux-armv7l-3.7/py3coap
  copying py3coap/__init__.py -> build/lib.linux-armv7l-3.7/py3coap
  copying py3coap/py3coap.py -> build/lib.linux-armv7l-3.7/py3coap
  running build_ext
  $ GOPATH=/tmp/tmp3j7er4c0 go get -d
  package github.com/moroen/gocoap/v2: cannot find package "github.com/moroen/gocoap/v2" in any of:
        /usr/lib/go-1.11/src/github.com/moroen/gocoap/v2 (from $GOROOT)
        /tmp/tmp3j7er4c0/src/github.com/moroen/gocoap/v2 (from $GOPATH)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-c6o1hici/py3coap/setup.py", line 22, in <module>
      scripts=["pycoap-client"],
    File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 161, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/dist-packages/setuptools/command/build_ext.py", line 87, in run
      _build_ext.run(self)
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-install-c6o1hici/py3coap/.eggs/setuptools_golang-2.1.1-py3.7.egg/setuptools_golang.py", line 140, in build_extension
      _check_call(cmd_get, cwd=pkg_path, env=env)
    File "/tmp/pip-install-c6o1hici/py3coap/.eggs/setuptools_golang-2.1.1-py3.7.egg/setuptools_golang.py", line 97, in _check_call
      subprocess.check_call(cmd, cwd=cwd, env=dict(os.environ, **env))
    File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '('go', 'get', '-d')' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for py3coap
  Running setup.py clean for py3coap
Failed to build py3coap
Installing collected packages: py3coap
    Running setup.py install for py3coap ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c6o1hici/py3coap/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c6o1hici/py3coap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ta9etho7/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/py3coap
         cwd: /tmp/pip-install-c6o1hici/py3coap/
    Complete output (55 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.7
    creating build/lib.linux-armv7l-3.7/py3coap
    copying py3coap/errors.py -> build/lib.linux-armv7l-3.7/py3coap
    copying py3coap/__init__.py -> build/lib.linux-armv7l-3.7/py3coap
    copying py3coap/py3coap.py -> build/lib.linux-armv7l-3.7/py3coap
    running build_ext
    $ GOPATH=/tmp/tmp3hnispem go get -d
    package github.com/moroen/gocoap/v2: cannot find package "github.com/moroen/gocoap/v2" in any of:
        /usr/lib/go-1.11/src/github.com/moroen/gocoap/v2 (from $GOROOT)
        /tmp/tmp3hnispem/src/github.com/moroen/gocoap/v2 (from $GOPATH)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-c6o1hici/py3coap/setup.py", line 22, in <module>
        scripts=["pycoap-client"],
      File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 161, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/dist-packages/setuptools/command/build_ext.py", line 87, in run
        _build_ext.run(self)
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-install-c6o1hici/py3coap/.eggs/setuptools_golang-2.1.1-py3.7.egg/setuptools_golang.py", line 140, in build_extension
        _check_call(cmd_get, cwd=pkg_path, env=env)
      File "/tmp/pip-install-c6o1hici/py3coap/.eggs/setuptools_golang-2.1.1-py3.7.egg/setuptools_golang.py", line 97, in _check_call
        subprocess.check_call(cmd, cwd=cwd, env=dict(os.environ, **env))
      File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '('go', 'get', '-d')' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c6o1hici/py3coap/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c6o1hici/py3coap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ta9etho7/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/py3coap Check the logs for full command output.
```

**Comment by moroen** [comment]
Sorry about that, I've inadvertently made a breaking change in one of the upstream golang modules, should be fixed no, so please try installing py3coap again...

**Comment by SANCLA** [comment]
Jup, that resolved the issue.
Just tested it all the way true (with again a clean install) and it works again.
Thanks mate!
