### ISSUE TITLE
Unable to add new devices.

### ISSUE THREAD

**Issue by Rednas79** [moroen/IKEA-Tradfri-plugin#140]
Hello

Added some new device to the Ikea gateway.
And trying to add them in Domoticz.

And i see the following error in domoticz

2021-10-16 17:16:45.003 Error: IKEA: (IKEA) ----> Line 778 in '/home/pi/domoticz/plugins/IKEA-Tradfri/plugin.py', function onStart
2021-10-16 17:16:45.003 Error: IKEA: (IKEA) ----> Line 594 in '/home/pi/domoticz/plugins/IKEA-Tradfri/plugin.py', function onStart
2021-10-16 17:16:45.003 Error: IKEA: (IKEA) ----> Line 382 in '/home/pi/domoticz/plugins/IKEA-Tradfri/plugin.py', function registerDevices
2021-10-16 17:16:45.003 Error: IKEA: (IKEA) ----> Line 109 in '/usr/local/lib/python3.7/dist-packages/tradfricoap/device.py', function Description
2021-10-16 17:16:45.003 Error: IKEA: (IKEA) ----> Line 163 in '/usr/local/lib/python3.7/dist-packages/tradfricoap/device.py', function State

If i do python3 plugin.py list
Lights: finds all of them
Plugs: find no the news one.

Traceback (most recent call last):
  File "plugin.py", line 139, in <module>
    process_args(args)
  File "/usr/local/lib/python3.7/dist-packages/tradfricoap/cli.py", line 175, in process_args
    list_devices(groups=True)
  File "/usr/local/lib/python3.7/dist-packages/tradfricoap/cli.py", line 273, in list_devices
    print("{}".format(dev.Description))
  File "/usr/local/lib/python3.7/dist-packages/tradfricoap/device.py", line 109, in Description
    self.DeviceID, self.Name, self.State, self.Level, self.Hex
  File "/usr/local/lib/python3.7/dist-packages/tradfricoap/device.py", line 163, in State
    return self.plugControl[constants.attrPlugState]
KeyError: '5850'

Pyhton version 3.7.3
Plugin 0.10.7

Update everything to the latest version, same issue.
Same error after a reboot of the PI

**Comment by moroen** [comment]
Could you post the output of the raw command for the device that fails?

**Comment by Rednas79** [comment]
Sorry, i add the device to the Ikea gateway via de Ikea App and Update the plugin to get the device listed in domoticz.
