### ISSUE TITLE
Status: 111 Description: Connection refused

### ISSUE THREAD

**Issue by raf6410** [moroen/IKEA-Tradfri-plugin#16]
Hello 

I follow all your install method for use your plugins. 
It works fine.
Thanks.
But i have a problem. it work only after 
` python3 tradfri.tac`

If i restart my raspberry PI3, Domoticz log say: 
Domoticz V3.8153 (c)2012-2017 GizMoCuz
2017-10-07 18:15:53.676 Build Hash: 494fff7, Date: 2017-07-30 12:19:41
2017-10-07 18:15:53.676 Startup Path: /home/pi/domoticz/
2017-10-07 18:15:53.863 Sunrise: 08:00:00 SunSet:19:16:00
2017-10-07 18:15:53.864 EventSystem: reset all events...
2017-10-07 18:15:54.126 PluginSystem: Started, Python version '3.5.3'.
2017-10-07 18:15:54.138 Active notification Subsystems: (0/12)
2017-10-07 18:15:54.158 WebServer(HTTP) started on address: :: with port 8080
2017-10-07 18:15:54.174 WebServer(SSL) started on address: :: with port 443
2017-10-07 18:15:54.176 Proxymanager started.
2017-10-07 18:15:54.178 Starting shared server on: :::6144
2017-10-07 18:15:54.178 TCPServer: shared server started...
2017-10-07 18:15:54.178 RxQueue: queue worker started...
2017-10-07 18:15:54.520 Incoming connection from: 192.168.1.20
2017-10-07 18:15:56.179 EventSystem: reset all events...
2017-10-07 18:15:56.180 EventSystem: reset all device statuses...
2017-10-07 18:15:56.375 PluginSystem: Entering work loop.
2017-10-07 18:15:56.380 Python EventSystem: Module not found - Trying to initialize.
2017-10-07 18:15:56.381 Python EventSystem: Initalizing event module.
2017-10-07 18:15:56.385 EventSystem: Started
2017-10-07 18:15:56.577 (Ikea) Initialized version 1.0.3, author 'moroen'
2017-10-07 18:15:56.645 PluginSystem: Starting I/O service thread.
2017-10-07 18:15:56.696 (Ikea) Failed to connect to IKEA tradfri COAP-adapter! Status: 111 Description: Connection refused
2017-10-07 18:16:10.120 PluginSystem: Starting I/O service thread.
2017-10-07 18:16:10.171 (Ikea) Failed to connect to IKEA tradfri COAP-adapter! Status: 111 Description: Connection refused
2017-10-07 18:16:16.082 PluginSystem: Starting I/O service thread.

Please could you help me ?

RAF6410

**Comment by moroen** [comment]
Are you running tradfri.tac  as a service, on linux preferably using systemd?

**Comment by raf6410** [comment]
yes i make  : 
`/domoticz/plugins/IKEA-Tradfri$ sudo cp ikea-tradfri.service /lib/systemd/system/
/domoticz/plugins/IKEA-Tradfri$ sudo systemctl daemon-reload
/domoticz/plugins/IKEA-Tradfri$ sudo systemctl start ikea-tradfri.service`

and modified my  ikea-tradfri.service file with my path of domoticz.

**Comment by moroen** [comment]
Glad it worked out!

**Comment by thepecca** [comment]
I'm having this same issue but it's caused by something else, at least I think. 

Last week the plugin stopped working for me, so after some digging i found that beacause of a Twisted compatibility issue an upgraded python, version 3.6, could solve the problem.

I tried but it didn't.

As I try to start the`tradfri.tac` service from the command line with python 3.4 i get the following:
`Traceback (most recent call last):
  File "tradfri.tac", line 13, in <module>
    from pytradfri import Gateway
  File "/usr/local/lib/python3.4/dist-packages/pytradfri/__init__.py", line 5, in <module>
    from .gateway import Gateway
  File "/usr/local/lib/python3.4/dist-packages/pytradfri/gateway.py", line 16, in <module>
    from .smart_task import SmartTask
  File "/usr/local/lib/python3.4/dist-packages/pytradfri/smart_task.py", line 34, in <module>
    from .util import BitChoices
  File "/usr/local/lib/python3.4/dist-packages/pytradfri/util.py", line 5, in <module>
    from typing import Union, List, Dict
ImportError: No module named 'typing'`

With Python 3.6 I get:
`Traceback (most recent call last):
  File "tradfri.tac", line 1, in <module>
    from twisted.conch.telnet import TelnetTransport, TelnetProtocol
ModuleNotFoundError: No module named 'twisted'`

what can I do?

Thanks in advance.

**Comment by moroen** [comment]
The twisted-modules appear not to be installed for python3.6.

On a linux-variant:

$ sudo pip3 install twisted

If that's not working, you might try:
$ python3.6 -m pip install twisted

**Comment by thepecca** [comment]
Unfortunately since I’m using a raspberry pi to run domoticz and the plugins and there is no version for python 3.6. When i try to install it i get:

‘Collecting twisted  Could not find a version that satisfies the requirement twisted (from versions: )No matching distribution found for twisted’

**Comment by moroen** [comment]
It doesn't? Oh... I stopped using a raspberry for Domoticz quite a while ago, so I'm not doing any testing on raspberry at the moment, perhaps I should start testing on the platform again... Anyway:

The error when using python 3.4 is in pytradfri, which some time ago started using the typing-library which was introduced in python 3.5... Python 3.5 is default on raspbian stretch, I think.

You could also revert to an older version of pytradfri, I can't remember at which version they started using typing.

As a last option, I'm currently creating a Ikea-tradfri server written in golang, along with a domoticz plugin,this might work better (Note: it's currently very basic and not well tested).

**Comment by moroen** [comment]
Ok, so I have been able to confirm that pytradfri and the plugin works with python3.5.3 on raspbian stretch, so you might want to go that route... 

BTW: According to the forum, quite a lot of users have trouble using the prebuilt Domoticz binaries on stretch, but compiling from source seems to work quite well!

**Comment by moroen** [comment]
Hope it works out, if not, reopen this issue or start a new one!
