### ISSUE TITLE
Exception, incorrect number of arguments

### ISSUE THREAD

**Issue by Cyberwizzard** [moroen/IKEA-Tradfri-plugin#22]
I set up a test copy of your plugin on my laptop to test how it works.

I got Domoticz up and running and it sees the plugin; I configured it and the prompt version does something. However it shows this:

Unhandled Error
Traceback (most recent call last):
  File "/home/cyberwizzard/.local/lib/python3.5/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/cyberwizzard/.local/lib/python3.5/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/cyberwizzard/.local/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/cyberwizzard/.local/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/cyberwizzard/.local/lib/python3.5/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/cyberwizzard/.local/lib/python3.5/site-packages/twisted/internet/tcp.py", line 205, in doRead
    return self._dataReceived(data)
  File "/home/cyberwizzard/.local/lib/python3.5/site-packages/twisted/internet/tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "tradfri.tac", line 76, in dataReceived
    self.factory.initGateway(self, command['gateway'], command['key'], command['observe'], command['pollinterval'], command['groups'])
  File "tradfri.tac", line 269, in initGateway
    self.devices = self.api(*self.api(self.gateway.get_devices()))
builtins.TypeError: request() takes 1 positional argument but 3 were given

Any idea what is going on?

**Comment by Cyberwizzard** [comment]
Error is due to the fact that the tradfri library being used is changing rapidly - so the instructions should point to installing a tag. I fixed the Dockerfile in #23, this also removed the error there.
