### ISSUE TITLE
No module "typing"

### ISSUE THREAD

**Issue by Reneke43** [moroen/IKEA-Tradfri-plugin#31]
What is wrong here? When I start **python3 tradfri.tac** I get this:

~/domoticz/plugins/IKEA-Tradfri $ python3 tradfri.tac
Traceback (most recent call last):
  File "tradfri.tac", line 13, in <module>
    from pytradfri import Gateway
  File "/usr/local/lib/python3.4/dist-packages/pytradfri/__init__.py", line 5, in <module>
    from .gateway import Gateway
  File "/usr/local/lib/python3.4/dist-packages/pytradfri/gateway.py", line 16, in <module>
    from .smart_task import SmartTask
  File "/usr/local/lib/python3.4/dist-packages/pytradfri/smart_task.py", line 34, in <module>
    from .util import BitChoices
  File "/usr/local/lib/python3.4/dist-packages/pytradfri/util.py", line 5, in <module>
    from typing import Union, List, Dict
ImportError: No module named 'typing'

**Comment by moroen** [comment]
This error is from pytradfri. It would appear that pytradfri now relies on the typing module, which I believe was introduced in python3.5... I would recommend trying to update your python version to 3.5.x
