### ISSUE TITLE
Connect/Disconnect loop

### ISSUE THREAD

**Issue by elxsi** [moroen/IKEA-Tradfri-plugin#32]
Hi,

I just updated domoticz to 3.8888 (compiled from sources, python 3.5) and now I'm having issues
with the tradfri plugin. The connection keeps bouncing with the following error message:

Connected from IPv4Address(TCP, '127.0.0.1', 56100)
Data received: b'{"action": "setConfig", "observe": "True", "gateway": "10.0.0.1", "pollinterval": "5", "psk": "<hidden>", "groups": "True", "identity": "Tradfri"}'
Initializing gateway
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/tcp.py", line 205, in doRead
    return self._dataReceived(data)
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/domoticz/plugins/IKEA-Tradfri/tradfri.tac", line 76, in dataReceived
    self.factory.initGateway(self, command)
  File "/home/domoticz/plugins/IKEA-Tradfri/tradfri.tac", line 275, in initGateway
    self.devices = self.api(self.api(self.gateway.get_devices()))
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 92, in request
    return self._execute(api_commands)
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 81, in _execute
    raise RequestTimeout() from None
pytradfri.error.RequestTimeout:

Disconnected

Any ideas what's going on here?

Thank you

**Comment by moroen** [comment]
The coap-adapter is unable to connect to the gateway for some reason. I'm just wondering about the IP-adress of the ikea-gateway, 10.0.0.1?

**Comment by elxsi** [comment]
Hi!

Yes, you're right. I've discovered that the device was gone some minutes ago, I think it crashed somehow. I'm closing this issue!

Thank you very much!
