### ISSUE TITLE
Error trying to start plugin: Transport is connecting.

### ISSUE THREAD

**Issue by Donniewiko** [moroen/IKEA-Tradfri-plugin#33]
I have tried and fixed numerous issues. But i cant seem to get this plugin to work.

Right now, my errorlog shows the following error (where lampen is the name of my devices):
2018-02-11 17:29:15.413 Error: CConnection_connect, connect request from 'Lampen' ignored. Transport is connecting.

I have verified that the pytradfri plugin is working from the commandline.
I get my list of devices, i can successfully turn a light on / off.

But i cant get it to work from Domoticz. It results in the error i posted above.
I have tried to create a PSK myself, and i also tried to use the generated PSK i get from the commandline;  i copied the Identity and key from the Tradfri_standalone_psk.conf .

need some advice on how to get this to work.
thanks in advance

**Comment by moroen** [comment]
Sorry for the late reply, I have been busy elsewhere for a while.. Could out please provide some more info from your log, preferably from domoticz starts up, IKEA-plugin initializing and to the error you have posted?

Regards,
M

**Comment by Donniewiko** [comment]
hi,
This is the (filtered) log. I used the name of my hardware device as the filter:

2018-02-14 20:31:06.215 (Lampen) Debug log level set to: 'true'.
2018-02-14 20:31:06.216 (Lampen) Heartbeat interval set to: 2.
2018-02-14 20:31:06.217 (Lampen) Protocol set to: 'JSON'.
2018-02-14 20:31:06.217 (Lampen) Transport set to: 'TCP/IP', 127.0.0.1:1234.
2018-02-14 20:31:06.226 (Lampen) Connect directive received, action initiated successfully.
2018-02-14 20:31:06.281 (Lampen) Calling message handler 'onConnect'.
2018-02-14 20:31:06.282 (Lampen) Failed to connect to IKEA tradfri COAP-adapter! Status: 111 Description: Connection refused
2018-02-14 20:31:15.523 (Lampen) Calling message handler 'onHeartbeat'.
2018-02-14 20:31:15.523 (Lampen) Not connected - nextConnect: 3
2018-02-14 20:31:17.523 (Lampen) Calling message handler 'onHeartbeat'.
2018-02-14 20:31:17.523 (Lampen) Not connected - nextConnect: 2
2018-02-14 20:31:19.513 (Lampen) Calling message handler 'onHeartbeat'.
2018-02-14 20:31:19.513 (Lampen) Not connected - nextConnect: 1
2018-02-14 20:31:19.513 (Lampen) Transport set to: 'TCP/IP', 127.0.0.1:1234.
2018-02-14 20:31:19.515 (Lampen) Connect directive received, action initiated successfully.
2018-02-14 20:31:19.565 (Lampen) Calling message handler 'onConnect'.
2018-02-14 20:31:19.566 (Lampen) Failed to connect to IKEA tradfri COAP-adapter! Status: 111 Description: Connection refused
2018-02-14 20:31:21.513 (Lampen) Calling message handler 'onHeartbeat'.
2018-02-14 20:31:21.513 (Lampen) Not connected - nextConnect: 3
2018-02-14 20:31:23.496 (Lampen) Calling message handler 'onHeartbeat'.
2018-02-14 20:31:23.497 (Lampen) Not connected - nextConnect: 2
2018-02-14 20:31:25.533 (Lampen) Calling message handler 'onHeartbeat'.
2018-02-14 20:31:25.533 (Lampen) Not connected - nextConnect: 1
2018-02-14 20:31:25.534 (Lampen) Transport set to: 'TCP/IP', 127.0.0.1:1234.
2018-02-14 20:31:25.535 (Lampen) Connect directive received, action initiated successfully.
2018-02-14 20:31:25.586 (Lampen) Calling message handler 'onConnect'.
2018-02-14 20:31:25.586 (Lampen) Failed to connect to IKEA tradfri COAP-adapter! Status: 111 Description: Connection refused
2018-02-14 20:31:27.503 (Lampen) Calling message handler 'onHeartbeat'.
2018-02-14 20:31:27.503 (Lampen) Not connected - nextConnect: 3
2018-02-14 20:31:29.543 (Lampen) Calling message handler 'onHeartbeat'.
2018-02-14 20:31:29.543 (Lampen) Not connected - nextConnect: 2
2018-02-14 20:31:31.527 (Lampen) Calling message handler 'onHeartbeat'.
2018-02-14 20:31:31.527 (Lampen) Not connected - nextConnect: 1
2018-02-14 20:31:31.528 (Lampen) Transport set to: 'TCP/IP', 127.0.0.1:1234.
2018-02-14 20:31:31.530 (Lampen) Connect directive received, action initiated successfully.
2018-02-14 20:31:31.580 (Lampen) Calling message handler 'onConnect'.
2018-02-14 20:31:31.580 (Lampen) Failed to connect to IKEA tradfri COAP-adapter! Status: 111 Description: Connection refused
2018-02-14 20:31:33.522 (Lampen) Calling message handler 'onHeartbeat'.
2018-02-14 20:31:33.523 (Lampen) Not connected - nextConnect: 3
2018-02-14 20:31:35.513 (Lampen) Calling message handler 'onHeartbeat'.
2018-02-14 20:31:35.514 (Lampen) Not connected - nextConnect: 2
2018-02-14 20:31:37.502 (Lampen) Calling message handler 'onHeartbeat'.
2018-02-14 20:31:37.502 (Lampen) Not connected - nextConnect: 1
2018-02-14 20:31:37.503 (Lampen) Transport set to: 'TCP/IP', 127.0.0.1:1234.
2018-02-14 20:31:37.504 (Lampen) Connect directive received, action initiated successfully.
2018-02-14 20:31:37.555 (Lampen) Calling message handler 'onConnect'.
2018-02-14 20:31:37.555 (Lampen) Failed to connect to IKEA tradfri COAP-adapter! Status: 111 Description: Connection refused
2018-02-14 20:31:39.514 (Lampen) Calling message handler 'onHeartbeat'.
2018-02-14 20:31:39.514 (Lampen) Not connected - nextConnect: 3

**Comment by moroen** [comment]
The plugin can't connect to the coap-adapter, are you sure it's running?

Try running the adapter from the command-line, make sure it starts and then restart domoticz again.

**Comment by Donniewiko** [comment]
Well i restarted the steps to install libcoap:

> checking for doxygen... no
> configure: WARNING: ==> Doxygen not found - continuing without Doxygen support
> configure: WARNING: ==> The libcoap html documentation will not be build!
> checking for a2x... no
> configure: WARNING: ==> You want to build the examples binaries, that is also in                                                                                                                                                             > cluding the respective manpages but a2x was not found!
> configure: error: ==> Install the package that contains the a2x binary or disabl                                                                                                                                                             > e the build of the examples using --disable-examples.
> **pi@raspberrypi:~/Downloads/libcoap $ make**
> make: *** No targets specified and no makefile found.  Stop.

So i couldn't finish the last 2 steps: Make and Make install

After that i still tried to test the PyTradfri plugin by starting the example script. But that crashes:

**python3 example_sync.py 192.168.1.5**
[<65538 - staande lamp (TRADFRI bulb E27 CWS opal 600lm)>, <65542 - huiskamer 2 (TRADFRI bulb GU10 WS 400lm)>, <65544 - eettafel (TRADFRI bulb E27 WS opal 980lm)>, <65541 - huiskamer 1 (TRADFRI bulb GU10 WS 400lm)>, <65539 - keuken 1 (TRADFRI bulb GU10 WS 400lm)>, <65540 - keuken 2 (TRADFRI bulb GU10 WS 400lm)>, <65545 - TV (TRADFRI bulb E14 WS opal 400lm)>]
Sleeping to start observation task
Received message for: <Light #0 - name: huiskamer 1, state: on, dimmer: 81, hex_color: efd275, xy_color: (32886, 27217), hsb_xy_color: (None, None, 81, 32886, 27217), supported features: 23 >
True
81
huiskamer 1
Received message for: <Light #0 - name: huiskamer 1, state: on, dimmer: 254, hex_color: efd275, xy_color: (32886, 27217), hsb_xy_color: (None, None, 254, 32886, 27217), supported features: 23 >
Received message for: <Light #0 - name: huiskamer 1, state: on, dimmer: 254, hex_color: efd275, xy_color: (32886, 27217), hsb_xy_color: (None, None, 254, 32886, 27217), supported features: 23 >
Received message for: <Light #0 - name: huiskamer 1, state: on, dimmer: 254, hex_color: f5faf6, xy_color: (24841, 24593), hsb_xy_color: (None, None, 254, 24841, 24593), supported features: 23 >
Received message for: <Light #0 - name: huiskamer 1, state: on, dimmer: 254, hex_color: f5faf6, xy_color: (24841, 24593), hsb_xy_color: (None, None, 254, 24841, 24593), supported features: 23 >
Traceback (most recent call last):
  File "example_sync.py", line 148, in <module>
    run()
  File "example_sync.py", line 135, in run
    print(tasks[0].task_control.tasks[0].transition_time)
  File "/home/pi/.local/lib/python3.5/site-packages/pytradfri/smart_task.py", line 270, in transition_time
    return self.raw.get(ATTR_TRANSITION_TIME) / 60 / 10
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'


I hope you can make something out of it, since i can't

grtz

**Comment by thepecca** [comment]
I'm also having this problem

**Comment by moroen** [comment]
Again, sorry for the late reply!

What are the output when trying to start the adapter from the command line:

$ domoticz/plugins/IKEA-Tradfri$ python3 tradfri.tac

Regards,
M

**Comment by Donniewiko** [comment]
```javascript
IKEA-tradfri COAP-adaptor version 0.5 started (command line)!
Connected from IPv4Address(TCP, '127.0.0.1', 59256)
Data received: b'{"groups": "True", "identity": "domoticz", "psk": "************", "pollinterval": "30", "gateway": "192.168.1.5", "observe": "True", "action": "setConfig"}'
Initializing gateway
Data received: b'{"action": "getLights"}'
{"action": "getLights", "result": [{"DeviceID": 65538, "HasRGB": true, "Name": "staande lamp", "Type": "Light", "HasWB": false, "Dimmable": true}, {"DeviceID": 65539, "HasRGB": false, "Name": "keuken 1", "Type": "Light", "HasWB": true, "Dimmable": true}, {"DeviceID": 65540, "HasRGB": false, "Name": "keuken 2", "Type": "Light", "HasWB": true, "Dimmable": true}, {"DeviceID": 65541, "HasRGB": false, "Name": "huiskamer 1", "Type": "Light", "HasWB": true, "Dimmable": true}, {"DeviceID": 65542, "HasRGB": false, "Name": "huiskamer 2", "Type": "Light", "HasWB": true, "Dimmable": true}, {"DeviceID": 65544, "HasRGB": false, "Name": "eettafel", "Type": "Light", "HasWB": true, "Dimmable": true}, {"DeviceID": 65545, "HasRGB": false, "Name": "TV", "Type": "Light", "HasWB": true, "Dimmable": true}, {"Name": "Group - huiskamer", "Type": "Group", "DeviceID": 156346, "HasWB": false, "Dimmable": true}, {"Name": "Group - keuken", "Type": "Group", "DeviceID": 133732, "HasWB": false, "Dimmable": true}], "status": "Ok"}
{'action': 'deviceUpdate', 'result': [{'Name': 'staande lamp', 'State': True, 'DeviceID': 65538, 'Hex': 'da5d41', 'Level': 254}], 'status': 'Ok'}
{'action': 'deviceUpdate', 'result': [{'Name': 'keuken 1', 'State': True, 'DeviceID': 65539, 'Hex': 'efd275', 'Level': 25}], 'status': 'Ok'}
{'action': 'deviceUpdate', 'result': [{'Name': 'keuken 2', 'State': True, 'DeviceID': 65540, 'Hex': 'efd275', 'Level': 25}], 'status': 'Ok'}
{'action': 'deviceUpdate', 'result': [{'Name': 'huiskamer 1', 'State': False, 'DeviceID': 65541, 'Hex': 'efd275', 'Level': 1}], 'status': 'Ok'}
{'action': 'deviceUpdate', 'result': [{'Name': 'huiskamer 2', 'State': False, 'DeviceID': 65542, 'Hex': 'efd275', 'Level': 119}], 'status': 'Ok'}
{'action': 'deviceUpdate', 'result': [{'Name': 'eettafel', 'State': True, 'DeviceID': 65544, 'Hex': 'f1e0b5', 'Level': 91}], 'status': 'Ok'}
{'action': 'deviceUpdate', 'result': [{'Name': 'TV', 'State': True, 'DeviceID': 65545, 'Hex': 'f1e0b5', 'Level': 137}], 'status': 'Ok'}
{'action': 'deviceUpdate', 'result': [{'Name': 'huiskamer', 'State': True, 'DeviceID': 156346, 'Level': 0}], 'status': 'Ok'}
{'action': 'deviceUpdate', 'result': [{'Name': 'keuken', 'State': True, 'DeviceID': 133732, 'Level': 0}], 'status': 'Ok'}

```

**Comment by moroen** [comment]
Strange... The adapter accepts connections and serves the devices info, but then it stops? The log from domoticz clearly indicates that the plugin can't connect to the adapter... I need to think about this...

**Comment by Donniewiko** [comment]
Let me know if you need some more info.

I am running Domoticz on a PI-1 

grtz

**Comment by moroen** [comment]
Closed, newer versions of the plugin is available. If it still fails, please reopen this issue.
