### ISSUE TITLE
Sending number of commands from group gives error

### ISSUE THREAD

**Issue by leejoow** [moroen/IKEA-Tradfri-plugin#4]
If I create a scene in Domoticz, which sets the level and WB of three lamps (so, six commands), the connection to is closed. In the Domoticz log the following is logged:

```
2017-08-15 19:04:40.823 (Tradfri) Exiting work loop...
2017-08-15 19:04:45.741 (Tradfri) Stopped.
2017-08-15 19:04:45.997 (Tradfri) Initialized version 1.0.0, author 'moroen' 
```

If I run the tradfri.tac from the shell, I see the following error happening:

```
Data received: b'{"level": 125, "action": "setLevel", "deviceID": "65543"}'
Data received: b'{"level": 125, "action": "setLevel", "deviceID": "65544"}'
Data received: b'{"level": 125, "action": "setLevel", "deviceID": "65538"}'
Data received: b'{"action": "setHex", "deviceID": "65538", "hex": "efd275"}'
Data received: b'{"action": "setHex", "deviceID": "65543", "hex": "efd275"}{"action": "setHex", "deviceID": "65544", "hex": "efd275"}'
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python3.4/dist-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python3.4/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.4/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python3.4/dist-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/local/lib/python3.4/dist-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/usr/local/lib/python3.4/dist-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "tradfri.tac", line 43, in dataReceived
    command = json.loads(data.decode("utf-8"))
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 346, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
builtins.ValueError: Extra data: line 1 column 59 - line 1 column 117 (char 58 - 116)

Disconnected
```

It appears the last command contains two JSON messages, which cannot be decoded by the coap adapter. Maybe there is a timing issue?

**Comment by moroen** [comment]
Thanks for bringing this to my attention. I thought I'd fixed this with the last commit, but apparently not... See if I can come up with a fix, or feel free to give it a try!
