### ISSUE TITLE
Problem with "non ascii" chars in room names

### ISSUE THREAD

**Issue by bilbolodz** [moroen/IKEA-Tradfri-plugin#54]
I've renamed room (and bulb) name into Android app using some "polish non special characters" (probably UTF8). Atfer that adapter crashed with an error (logs bellow). Removing "special characters" from names solves problem.

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "tradfri.tac", line 90, in dataReceived
    self.factory.initGateway(self, command)
  File "tradfri.tac", line 369, in initGateway
    self.groups = self.api(self.api(self.gateway.get_groups()))
  File "/usr/local/lib/python3.5/dist-packages/pytradfri-6.0.1-py3.5.egg/pytradfri/api/libcoap_api.py", line 101, in request
    
  File "/usr/local/lib/python3.5/dist-packages/pytradfri-6.0.1-py3.5.egg/pytradfri/api/libcoap_api.py", line 83, in _execute
    
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 385, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.5/subprocess.py", line 801, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1485, in _communicate
    self.stdout.encoding)
  File "/usr/lib/python3.5/subprocess.py", line 705, in _translate_newlines
    data = data.decode(encoding)
builtins.UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)

**Comment by moroen** [comment]
I need to investigate a bit further, but at first glance, this appear to be a pytradfri-issue?

**Comment by kristianschneider** [comment]
I had the same problem with Danish. Its a pytradfri problem. I ended up renaming ascii characters

**Comment by moroen** [comment]
Upstream issue, closing
