### ISSUE TITLE
Error in initGateway: Request timeout

### ISSUE THREAD

**Issue by MHagreis** [moroen/IKEA-Tradfri-plugin#73]
afther the last update IKEA hub i now get Error in initGateway: Request timeout

python3 tradfri.tac --dryrun
IKEA-tradfri COAP-adaptor version 0.8.8 started (command line)!
Initializing gateway
Transitiontime: 10
Error in initGateway: Request timeout
Traceback (most recent call last):
  File "tradfri.tac", line 230, in initGateway
    self.devices = self.api(self.api(self.gateway.get_devices()))
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", li                                                                                        ne 96, in request
    return self._execute(api_commands, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", li                                                                                        ne 85, in _execute
    raise RequestTimeout() from None
pytradfri.error.RequestTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tradfri.tac", line 441, in <module>
    AdaptorFactory()).addErrback(error)
  File "tradfri.tac", line 154, in __init__
    self.initGateway(None, None)
  File "tradfri.tac", line 235, in initGateway
    client.transport.loseConnection()
AttributeError: 'NoneType' object has no attribute 'transport'

what am i doing wrong ?

**Comment by moroen** [comment]
Try generating a new IDENT/PSK-pair...

**Comment by MHagreis** [comment]
This didn't work , also time out error

Changed hardware setting to polling interval 300 and added a tradfri repeater there by creating an more stable zigbee mash looks like that did the trick will monitor for this week keep you posted

**Comment by moroen** [comment]
I'm closing this, please feel free to reopen if needed! :)
