### ISSUE TITLE
Address already in use at server debug

### ISSUE THREAD

**Issue by jeroenzelle** [moroen/IKEA-Tradfri-plugin#82]
Hi,

I have configured my Pi 4 with your manual to add the Trafdri plugin to Domoticz. After config it did not appear as a hardware device, so I opened the server debug.

The error in there is:
```
(myvenv) pi@domoticz:~/domoticz/plugins/IKEA-Tradfri $ tradfri -vv server
INFO:Starting IKEA-Tradfri HTTP server 0.2.0 on 127.0.0.1:8086
ERROR:Task exception was never retrieved
future: <Task finished coro=<tcp_server.main() done, defined at /home/pi/domoticz/plugins/IKEA-Tradfri/myvenv/lib/python3.7/site-packages/ikeatradfri-0.0.1-py3.7.egg/ikeatradfri/tcp_server.py:244> exception=OSError(98, "error while attempting to bind on address ('127.0.0.1', 1235): address already in use")>
Traceback (most recent call last):
  File "/home/pi/domoticz/plugins/IKEA-Tradfri/myvenv/lib/python3.7/site-packages/ikeatradfri-0.0.1-py3.7.egg/ikeatradfri/tcp_server.py", line 249, in main
    self.handle_echo, hostConfig["Server_ip"], hostConfig["Tcp_port"]
  File "/usr/lib/python3.7/asyncio/streams.py", line 114, in start_server
    return await loop.create_server(factory, host, port, **kwds)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1378, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 1235): address already in use
ERROR:Task exception was never retrieved
future: <Task finished coro=<start() done, defined at /home/pi/domoticz/plugins/IKEA-Tradfri/myvenv/lib/python3.7/site-packages/ikeatradfri-0.0.1-py3.7.egg/ikeatradfri/http_server.py:18> exception=OSError(98, "error while attempting to bind on address ('127.0.0.1', 8086): address already in use")>
Traceback (most recent call last):
  File "/home/pi/domoticz/plugins/IKEA-Tradfri/myvenv/lib/python3.7/site-packages/ikeatradfri-0.0.1-py3.7.egg/ikeatradfri/http_server.py", line 38, in start
    await site.start()
  File "/home/pi/domoticz/plugins/IKEA-Tradfri/myvenv/lib/python3.7/site-packages/aiohttp/web_runner.py", line 102, in start
    reuse_port=self._reuse_port)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1378, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 8086): address already in use
```

As you can see I already tried to change the ports to have it working, but that did not solve the issue.

Any tips for how to solve this?

Kind regards,
Jeroen Zelle

**Comment by jeroenzelle** [comment]
Posted it in the correct forum instead of on Git
